#!/bin/bash

set -e

#if dpkg-query -l | grep -q grub-common; then
#    dfile=/usr/share/locale/ko/LC_MESSAGES/grub-common-grub.mo
#    diverter=$(dpkg-divert --listpackage $dfile)
#
#    if [ "$diverter" != "grub-common" ]; then
#      dpkg-divert --package grub-common \
#                  --rename \
#                  --divert $dfile /usr/share/locale/ko/LC_MESSAGES/grub.mo
#    fi
#fi

exit 0;
